spring:
  datasource:
    url: jdbc:mysql://localhost:3306/happyhotel
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true