spring:
#  web:
#    resources:
#      static-locations: classpath:/static/
  mvc:
    static-path-pattern: '/static/**'

  datasource:
    url: jdbc:mysql://localhost:3306/${DB_NAME}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

toss:
  secret: ${TOSS_SECRET}

jwt:
  secret: ${JWT_SECRET}

